fix: use np.ndarray in GridWithPoints and MultiPoseOctree
true-real-michael/octreelib pull request #10
Opened 2023-10-27 09:02 UTC by true-real-michael

2023-10-29 08:03 UTC, pmokeev requested changes
Пока без документации это трудно читать :disappointed:

2023-10-29 08:03 UTC, pmokeev commented on octreelib/internal/point.py
> +RawPointCloud = Annotated[npt.NDArray[np.float_], Literal["N", 3]]
Почему оно не в typing файле?

2023-10-29 08:03 UTC, pmokeev commented on octreelib/internal/point.py
> +# for having and not having information about pose number.
Документация в питоне делается не так

2023-10-29 08:03 UTC, pmokeev commented on octreelib/internal/point.py
> +        # Construct from existing np.ndarray.
Ужс

2023-10-30 09:39 UTC, true-real-michael commented on octreelib/internal/point.py
> +RawPointCloud = Annotated[npt.NDArray[np.float_], Literal["N", 3]]
потому что весь этот файл отвечает за Точки и назван point.py
можно сделать модуль typing и туда это запихнуть вместе с typing.py

2023-10-30 09:40 UTC, true-real-michael commented on octreelib/internal/point.py
> +        # Construct from existing np.ndarray.
https://numpy.org/doc/stable/user/basics.subclassing.html

2023-11-04 20:22 UTC, closed without merging