Grid
true-real-michael/octreelib pull request #11
Opened 2023-10-31 11:51 UTC by true-real-michael

2023-11-01 10:49 UTC, pmokeev requested changes
Давай еще сортировать импорты 3rd party imports -> std imports -> same library imports. Можешь у меня конфигу isort в репозитории посмотреть

2023-11-01 10:49 UTC, pmokeev commented on octreelib/grid/__init__.py
> +This module contains base classes and implementations for Grid, GridConfig, GridWithPoints
Кто такой `GridWithPoints`? 😄

2023-11-01 10:49 UTC, pmokeev commented on octreelib/grid/grid.py
> +        self.grid_config.octree_type = MultiPoseOctree
`__octree_type` ? Здесь и ниже, вроде не хотим на публику показывать эти поля

2023-11-01 10:49 UTC, pmokeev commented on octreelib/grid/grid.py
> +    The space is divided into the grid of voxels with the given edge_size.
`edge_size` это же начальный размер вокселя?

2023-11-01 10:49 UTC, pmokeev commented on octreelib/grid/grid.py
> +        self.octrees: Dict[Tuple[float, float, float], grid_config.octree_type] = {}
`Tuple[float, float, float]` это поди какой-нибудь `Array3[float]` из `typing.py`?

2023-11-01 10:49 UTC, pmokeev commented on octreelib/grid/grid.py
> +        If an octree for this pos does not exist, a new octree is created
Who is pos? Pose?

2023-11-01 10:49 UTC, pmokeev commented on octreelib/grid/grid.py
> +        :param pose_number: pos to which the cloud is inserted
Прикольно, это типа в питоне двумя способами можно параметры в докстрингах писать?

2023-11-01 10:49 UTC, pmokeev commented on octreelib/grid/grid.py
> +        # register pose if it is not registered yet
`is hasn't been registered yet`

2023-11-01 10:49 UTC, pmokeev commented on octreelib/grid/grid.py
> +        Subdivides all octrees based on all points and given filtering criteria.
`given subdividing criteria`

2023-11-01 10:49 UTC, pmokeev commented on octreelib/grid/grid.py
> +    def n_leaves(self, pose_number: int) -> int:
Я сделала больно и покинула чат? Кто `leaves`? 😄

2023-11-01 10:49 UTC, pmokeev commented on octreelib/grid/grid_base.py
> +        :return: List of
List of what?

2023-11-01 10:49 UTC, pmokeev commented on octreelib/internal/box.py
> +    corner_b: RawPoint
Что-то беды с неймингом и документацией. Бтв corner_a и corner_b не лучший вариант, может быть как-то все же связать это с верхний(максимальный)/нижний(минимальный)?

2023-11-01 10:49 UTC, pmokeev commented on requirements.txt
> +pytest
Версий бы

2023-11-01 10:49 UTC, pmokeev commented on octreelib/internal/box.py
> +    def __post_init__(self):
А оно используется где-то?

2023-11-01 10:49 UTC, pmokeev commented on octreelib/internal/box.py
> +    def __post_init__(self):
Или это проверка ради проверки

2023-11-01 10:49 UTC, pmokeev commented on octreelib/internal/interfaces.py
> +    def __init__(self, _id: Optional[int] = None):
Инит наверное все же выше `property` должен быть.

2023-11-01 10:49 UTC, pmokeev commented on octreelib/internal/voxel.py
> +_static_voxel_id_map = {}
Почему?

2023-11-01 10:49 UTC, pmokeev commented on octreelib/internal/voxel.py
> +        other_hashable = _point_to_hashable(corner + edge_length)
Who is other?

2023-11-01 10:49 UTC, pmokeev commented on octreelib/octree/multi_pose_octree.py
> +def _filter_by_pose_number(pose_number: int, points: PosePointCloud) -> PosePointCloud:
почему?

2023-11-01 10:49 UTC, pmokeev commented on octreelib/octree/multi_pose_octree.py
> +    def n_leaves_for_pose(self, pose_number: int) -> int:
Почему leaves если leafs?

2023-11-01 10:49 UTC, pmokeev commented on octreelib/octree/octree.py
> +    def n_leaves(self):
Ну ты понял

2023-11-01 10:49 UTC, pmokeev commented on test/grid/__init__.py
А почему оно пустое?

2023-11-01 10:49 UTC, pmokeev commented on octreelib/internal/box.py
> +    This class represents a box object.
Вообще не понятно что за box object

2023-11-01 10:49 UTC, pmokeev commented on octreelib/internal/point.py
> +        # Construct from existing np.ndarray.
А где докстринг?

2023-11-01 10:49 UTC, pmokeev commented on octreelib/internal/point.py
> +        # Construct from existing np.ndarray.
А где докстринг?

2023-11-01 10:49 UTC, pmokeev commented on octreelib/internal/voxel.py
> +    Voxel with a mutable point cloud.
А зачем нам immutable StaticStoringVoxel?

2023-11-01 10:51 UTC, true-real-michael commented on octreelib/grid/grid.py
> +        self.octrees: Dict[Tuple[float, float, float], grid_config.octree_type] = {}
нет, он нехешируемый

2023-11-01 10:52 UTC, true-real-michael commented on octreelib/grid/grid.py
> +    The space is divided into the grid of voxels with the given edge_size.
именно так

2023-11-01 10:53 UTC, true-real-michael commented on octreelib/grid/__init__.py
> +This module contains base classes and implementations for Grid, GridConfig, GridWithPoints
ы

2023-11-01 11:09 UTC, true-real-michael commented on octreelib/grid/grid.py
> +        self.grid_config.octree_type = MultiPoseOctree
поменял на `_grid_config`
его мы хотим сделать protected
`octree_type` внутри конфига не делаю private/protected, поскольку это датакласс

2023-11-01 11:14 UTC, true-real-michael commented on octreelib/grid/grid.py
> +    def n_leaves(self, pose_number: int) -> int:
была опечатка `leafs`

2023-11-01 11:15 UTC, true-real-michael commented on octreelib/grid/grid_base.py
> +        :return: List of
😁😁😁

2023-11-01 11:17 UTC, true-real-michael commented on octreelib/grid/grid.py
> +        :param pose_number: pos to which the cloud is inserted
я, кажется, везде пишу одним способом

2023-11-01 11:21 UTC, true-real-michael commented on octreelib/internal/box.py
> +    def __post_init__(self):
Проверка нужна, чтобы не задать невалидные значения углов
Используется, например, (здесь)[https://github.com/true-real-michael/octreelib/blob/140c77781842d7f51e7930efc4e5afc7805d797a/octreelib/octree/multi_pose_octree.py#L141]

2023-11-01 11:26 UTC, true-real-michael commented on octreelib/internal/voxel.py
> +_static_voxel_id_map = {}
Хотим задавать одинаковые айди для разных вокселей, у которых одинаковые corner и edge_size
Их, конечно, счетное число, но для генерации айдишников умным способом нужны данные сетки (какой corner у сетки, какой изначальный grid_voxel_edge_size), поэтому сделал по-тупому: проверяем, есть ли такой воксель или нет. Если есть, то берем уже существующий айди, иначе делаем новый

2023-11-01 11:26 UTC, true-real-michael commented on octreelib/octree/multi_pose_octree.py
> +def _filter_by_pose_number(pose_number: int, points: PosePointCloud) -> PosePointCloud:
?

2023-11-01 11:27 UTC, true-real-michael commented on octreelib/octree/multi_pose_octree.py
> +    def n_leaves_for_pose(self, pose_number: int) -> int:
везде поменял leafs на leaves, это была опечатка, которая долго держалась

2023-11-01 11:36 UTC, pmokeev commented on octreelib/grid/grid.py
> +        :param pose_number: pos to which the cloud is inserted
[Ориентируясь на либу Кирилла, там покрасивше докстринги](https://github.com/prime-slam/evolin/blob/main/evolin/metrics/association/pose_error/pose_error_.py#L34)

2023-11-01 12:13 UTC, true-real-michael commented on octreelib/internal/voxel.py
> +    Voxel with a mutable point cloud.
Чтобы возвращать в Grid.get_leaf_points
Например, [здесь](https://github.com/true-real-michael/octreelib/blob/140c77781842d7f51e7930efc4e5afc7805d797a/octreelib/octree/multi_pose_octree.py#L141)

Не хотим возвращать воксель, который в сетке, потому что один subdivide / filter, и все точки уйдут в дочерние воксели / часть точек пропадет

Из-за этого создаем немутабельную копию и возвращаем пользователю

2023-11-01 12:24 UTC, pmokeev commented on octreelib/grid/grid.py
> +        :param pose_number: pos to which the cloud is inserted
https://github.com/pmokeev/voxel-slam/blob/main/slam/pipeline/pipeline.py#L16

2023-11-01 13:47 UTC, anastasiia-kornilova commented on octreelib/grid/grid_base.py
> +    grid_voxel_edge_length: size of a minimal possible voxel, the octree will be able to subdivide to
Строчкой выше есть параметр `debug`, непонятно, что он вообще делает (какая-то визуализация появляется? логгирование?)

2023-11-01 13:49 UTC, anastasiia-kornilova commented on octreelib/grid/grid.py
> +        if pose_number not in self.__pose_voxel_coordinates:
Не уверена, что мы дважды хотим добавлять точки в одну и ту же позу. Это явно признак того, что юзер что-то перепутал. Может быть стоит бросать исключение, если поза уже есть?

2023-11-01 13:57 UTC, pmokeev requested changes

2023-11-01 13:57 UTC, pmokeev commented on octreelib/grid/__init__.py
> +import octreelib.grid.grid as grid_with_points_module
Есть три вида лжи: ложь, нагла ложь, и `import octreelib.grid.grid as grid_with_points_module`

2023-11-01 13:57 UTC, pmokeev commented on octreelib/grid/grid.py
> +from typing import List, Dict, Callable, Tuple
А чево импорты по старому? Или хочешь в следующем PRе это дело исправить
![image](https://github.com/true-real-michael/octreelib/assets/75482510/be20d1ae-465a-40c1-a035-e932c3ea4074)

2023-11-01 13:57 UTC, pmokeev commented on octreelib/grid/grid.py
> +    Each voxel in a grid stores points in the form of a MultiPoseOctree.
`MultiPoseOctree` кажется тоже уже нет никакого

2023-11-01 13:57 UTC, pmokeev commented on octreelib/grid/grid.py
> +    Each voxel in a grid stores points in the form of a MultiPoseOctree.
И тут еще в докстринг можно добавить параметр для конструктора, [like this](https://github.com/pmokeev/voxel-slam/blob/main/slam/backend/mrob_backend.py#L17)

2023-11-01 13:57 UTC, pmokeev commented on octreelib/grid/grid.py
> +        self._grid_config.octree_type = MultiPoseOctree
А почему мы не можем хранить целиковый `GridConfig`?

2023-11-01 13:57 UTC, pmokeev commented on octreelib/grid/grid.py
> +        self._grid_config.octree_type = MultiPoseOctree
Кмк странно что мы прокидываем этот класс только ради `octree_type`

2023-11-01 13:57 UTC, pmokeev commented on octreelib/grid/grid.py
> +        self.__octrees: Dict[Tuple[float, float, float], grid_config.octree_type] = {}
Ну может его зааннотировать тогда как-нибудь этот `Tuple[float, float, float]` ? А то внешнему зрителю ничего не понятно чо за тапл

2023-11-01 13:57 UTC, pmokeev commented on octreelib/grid/grid.py
> +    def _get_voxel_for_point(self, point: RawPoint) -> RawPoint:
А почему protected, а не private?

2023-11-01 13:57 UTC, pmokeev commented on octreelib/grid/grid_base.py
> +    grid_voxel_edge_size: int = 1
Так, это начальный все же размер, или минимальный конечный?
`grid_voxel_edge_length: size of a minimal possible voxel, the octree will be able to subdivide to`
Чот меня документация путает

2023-11-01 13:57 UTC, pmokeev commented on octreelib/internal/box.py
> +    This class represents a box in 3D space.
Напиши тут чем Box от Voxel отличается, я потому что все еще не понимаю

2023-11-01 13:57 UTC, pmokeev commented on octreelib/internal/box.py
> +    def __post_init__(self):
По ссылке вызов метода `is_point_inside`

2023-11-01 13:57 UTC, pmokeev commented on octreelib/internal/point.py
> +        # Construct from existing np.ndarray.
А? 
![Uploading image.png…]()

2023-11-01 13:57 UTC, pmokeev commented on octreelib/internal/voxel.py
> +_static_voxel_id_map = {}
Я про обособленность поля. Его никуда не втащить?

2023-11-01 13:57 UTC, pmokeev commented on octreelib/internal/voxel.py
> +        corner_max_hashable = _point_to_hashable(corner + edge_length)
`hashed_min_corner` мб? И _point_to_hashable тоже так себе название функции: `hash_point` мб? Необходимо отразить действие глаголом

2023-11-01 13:57 UTC, pmokeev commented on octreelib/internal/voxel.py
> +        self.edge_length = edge_length
Зочем они публичные?

2023-11-01 13:57 UTC, pmokeev commented on octreelib/internal/voxel.py
> +        edge_length: np.float_,
Да можно наверное православный `float` просто

2023-11-01 13:57 UTC, pmokeev commented on octreelib/internal/voxel.py
> +    Voxel with a mutable point cloud.
А если `copy.deepcopy` делать? Как будто бы одна из этих сущностей не сильно нужна

2023-11-01 13:57 UTC, pmokeev commented on octreelib/octree/multi_pose_octree.py
> +    def n_leaves_for_pose(self, pose_number: int) -> int:
Да, my bad. Не знал что plural от leaf это leaves

2023-11-01 13:57 UTC, pmokeev commented on octreelib/octree/multi_pose_octree.py
> +class MultiPoseOctree(Octree):
А почему мы этот `MultiPoseOctree` просто `Octree` не обзовем, а тот не выпилим?

2023-11-01 14:32 UTC, true-real-michael commented on octreelib/internal/box.py
> +    def __post_init__(self):
если ты про `__post_init__`, то он вызывается каждый раз при создании объекта box

2023-11-01 14:34 UTC, true-real-michael commented on octreelib/grid/__init__.py
> +import octreelib.grid.grid as grid_with_points_module
💀

2023-11-02 08:22 UTC, true-real-michael commented on octreelib/internal/voxel.py
> +    Voxel with a mutable point cloud.
В любом случае, если мы будем возвращать пользователю объект OctreeNode, то у него будет доступ к методам subdivide, map_leaf_points, n_nodes, и прочим. И эти методы не имеют смысла вне октодерева, и следовательно, возвращать их из октодерева куда-то еще неуместно.

2023-11-02 08:23 UTC, true-real-michael commented on octreelib/grid/grid_base.py
> +    grid_voxel_edge_length: size of a minimal possible voxel, the octree will be able to subdivide to
Создано с прицелом на логгирование, которое пока не добавлено

2023-11-02 08:26 UTC, true-real-michael commented on octreelib/grid/grid.py
> +        if pose_number not in self.__pose_voxel_coordinates:
Это было в StaticGrid. Могу вернуть эту логику.

2023-11-02 08:38 UTC, true-real-michael commented on octreelib/grid/grid.py
> +    Each voxel in a grid stores points in the form of a MultiPoseOctree.
есть есть

2023-11-02 09:00 UTC, true-real-michael commented on octreelib/octree/multi_pose_octree.py
> +class MultiPoseOctree(Octree):
Тогда будет библиотека octreelib, которая не умеет делать октодеревья для обычных точек без поз😁

2023-11-02 09:27 UTC, true-real-michael commented on octreelib/grid/grid.py
> +        self._grid_config.octree_type = MultiPoseOctree
мы [храним](https://github.com/true-real-michael/octreelib/blob/613fc1852e943bd62019466579b3819af14a46be/octreelib/grid/grid_base.py#L47) целиковый GridConfig

2023-11-02 10:50 UTC, true-real-michael commented on octreelib/internal/box.py
> +    This class represents a box in 3D space.
Voxel -- это куб, он хранит точки, имеет id, взаимодействует с октодеревьями и узлами октодеревьев.
Box -- это параллелограмм, причем чисто геометрический, если угодно, это обертка над Tuple[Point, Point] + пара геометрических методов.
Удалить Box мы не можем, потому что нам важно, что он не куб, а параллелограмм.
Отнаследоваться мы тоже не можем, см. https://en.wikipedia.org/wiki/Circle–ellipse_problem

2023-11-02 11:01 UTC, pmokeev commented on octreelib/internal/voxel.py
> +    Voxel with a mutable point cloud.
Так у тебя же `OctreeNode` все равно public класс. В чем проблема?

2023-11-02 11:31 UTC, true-real-michael commented on octreelib/internal/voxel.py
> +    Voxel with a mutable point cloud.
В таком случае, кмк, правильнее будет сделать `OctreeNode` приватным

2023-11-02 11:49 UTC, pmokeev requested changes

2023-11-02 11:49 UTC, pmokeev commented on octreelib/grid/grid.py
> +from typing import List, Dict, Callable, Tuple
А чево резолв? Давай какую-нибудь карточку хотя бы заведем на форматирование импортов
![image](https://github.com/true-real-michael/octreelib/assets/75482510/3b75ac5b-6c08-4b73-ab38-a7cf015e45e7)

2023-11-02 11:49 UTC, pmokeev commented on octreelib/grid/grid.py
> +        self._grid_config.octree_type = MultiPoseOctree
А почему мы при инициализации grid_config не можем тип октодерева задавать?

2023-11-02 11:49 UTC, pmokeev commented on octreelib/grid/grid.py
> +            voxel_coordinates_hashable = get_hashable_from_point(voxel_coordinates)
Плохой нейминг как для переменной, так и для функции. Hashable это свойство чего-то, как хешируемый. Функция должна быть захешировать, переменная hashed_voxel_coordinates

2023-11-02 11:49 UTC, pmokeev commented on octreelib/internal/box.py
> +    This class represents a box in 3D space.
1) Имел ввиду в докстринге напиши чем отличатеся
2) А где используется этот параллелограм? Просто нейминг немного сбивает с толку, что за коробка?

2023-11-02 11:49 UTC, pmokeev commented on octreelib/internal/point.py
> +        # Construct from existing np.ndarray.
Так где докстринг то? 😄

2023-11-02 11:49 UTC, pmokeev commented on octreelib/internal/point.py
> +        # Construct from existing np.ndarray.
Так где докстринг то? 😄

2023-11-02 11:49 UTC, pmokeev commented on octreelib/internal/point.py
> +def get_hashable_from_point(point: RawPoint) -> HashablePoint:
Про нейминг писал. А может это методом Point сделать? Вроде же есть `__hash__`

2023-11-02 11:49 UTC, pmokeev commented on octreelib/internal/voxel.py
> +        hashable_corner_max = get_hashable_from_point(corner + edge_length)
Писал про hashable

2023-11-02 11:49 UTC, pmokeev commented on octreelib/octree/multi_pose_octree.py
> +class MultiPoseOctree(Octree):
Хм, окей. Но я попозже нарисую схему классов и вернусь к этому еще

2023-11-02 15:13 UTC, pmokeev commented
Помимо выше-перечисленного, архитектурно:
- `Voxel`: `corner` и `corners`, из нейминга непонятно какой именно `corner`. Corner либо выпилить (т.к. есть `corners`), либо переименовать как-то
- `Voxel` -> `VoxelBase`
- `StoringVoxel` -> `Voxel`
- `StaticStoringVoxel` можно удалить, если в интерфейсе возвращать `Voxel`, добавив метод `get_points` у `Voxel`
- Не нужно `protected` поля выносить из `__init__`, если инициализируешь их там
- В `OctreeBase` можно втащить абстрактный `get_points`
- `points_a`, `points_b` — в одном месте увидел
- Странно видеть `_empty_point_cloud` `@property`
- Всякие методы в `MultiPoseOctree` стоит, наверное, переименовать в `get_leaf_points_by_pose_number`
- `__get_voxel_for_point` наверное стоит спустить вниз класса
- В связи со скорым переименованием `Segmenters` в `PlaneEstimators`, наверное можно переименовать `map_leaf_points` в `estimate_planes`. Но это так, на будущее
- Всякие `n_leaves_for_pose` (и подобное) наверное можно будет на `np.where` в будущем перетащить, чтобы ускорить это дело

2023-11-03 10:48 UTC, true-real-michael commented on octreelib/grid/grid.py
> +        self._grid_config.octree_type = MultiPoseOctree
Можем, точнее могли в StaticGrid
С этим типом грида совместим только MultiPoseOctree
Думаю, это нужно оставить, но придумать какие-то ограичения на то, какие типы октодерева мы можем использовать, чтобы не было таких костылей

2023-11-03 10:51 UTC, true-real-michael commented on octreelib/internal/box.py
> +    This class represents a box in 3D space.
так, ошибся в терминах
прямоугольный параллелепипед ака кубоид, а не параллелограмм (11 класс, привет)

2023-11-03 11:01 UTC, true-real-michael commented on octreelib/internal/box.py
> +    This class represents a box in 3D space.
Где используется — в случаях, когда мы хотим получить bounding_box чего-то и когда мы хотим проверить, лежит ли точка в коробке, например:

- https://github.com/true-real-michael/octreelib/blob/931626eefac6c12164262fffd78f89313d18e2ac/octreelib/octree/octree.py#L33
- https://github.com/true-real-michael/octreelib/blob/92409b33d9d6829456f64596a1db1e32ed7dd80b/octreelib/internal/voxel.py#L50
- https://github.com/true-real-michael/octreelib/blob/931626eefac6c12164262fffd78f89313d18e2ac/octreelib/octree/octree.py#L21

2023-11-03 11:05 UTC, true-real-michael commented on octreelib/internal/voxel.py
> +    Voxel with a mutable point cloud.
Кейсы использования этого класса — когда мы даем юзеру коробку с облаком точек, и все
Важна только сама коробка (ее размеры и расположение), и точки 
А если использовать OctreeNode, то у пользователя будет куча бесполезных для него методов и свойств

2023-11-03 11:23 UTC, true-real-michael commented on octreelib/internal/voxel.py
> +    Voxel with a mutable point cloud.
Вариант решения -- сделать SoringVoxel наследником StaticStoringVoxel, и просто апкастить self
<img width="752" alt="Screenshot 2023-11-03 at 14 23 18" src="https://github.com/true-real-michael/octreelib/assets/64229743/e506bb48-322a-4253-888e-700114f3bb28">

2023-11-03 11:33 UTC, true-real-michael commented on octreelib/grid/grid.py
> +from typing import List, Dict, Callable, Tuple
Создал карточки
[формат импортов](https://www.notion.so/15a1646f79564151bdbd6078f1656107?pvs=4)
[формат документации](https://www.notion.so/numpydoc-63888ce76fde4f6b8ae66442fa20518b?pvs=4)

2023-11-03 12:54 UTC, true-real-michael commented
@pmokeev 

> * `Voxel`: `corner` и `corners`, из нейминга непонятно какой именно `corner`. Corner либо выпилить (т.к. есть `corners`), либо переименовать как-то

Переименовал в `corner_min`, как в Box. `corners` переименовал в `all_corners`.

> * `Voxel` -> `VoxelBase`
> * `StoringVoxel` -> `Voxel`
> * `StaticStoringVoxel` можно удалить, если в интерфейсе возвращать `Voxel`, добавив метод `get_points` у `Voxel`

Сделал немного иначе, но смысл сохраняется: висячий класс `StaticStoringVoxel` удален.

> * Странно видеть `_empty_point_cloud` `@property`

перетащил в PointCloud, PosePointCloud в качестве classmethod.

> * В связи со скорым переименованием `Segmenters` в `PlaneEstimators`, наверное можно переименовать `map_leaf_points` в `estimate_planes`. Но это так, на будущее

Библиотека ни про какие плоскости не знает, для нее это просто какие-то преобразования облаков точек, не более.
Энивей, это уже в следующих ПРах.

> * Всякие `n_leaves_for_pose` (и подобное) наверное можно будет на `np.where` в будущем перетащить, чтобы ускорить это дело

Это, думаю, уже в следующих ПРах.

2023-11-04 12:07 UTC, pmokeev approved these changes

2023-11-04 12:11 UTC, merged