feat(visualisation): add visualise method for Grid
true-real-michael/octreelib pull request #13
Opened 2023-11-02 15:44 UTC by pmokeev

What this PR contains:
- Method visualize for Grid visualizing: it produces `.html` file with points (random colors) and **non-empty** voxels edges (red color)

In future it would be nice to also handle visualizing non-empty voxels

2023-11-03 14:52 UTC, true-real-michael requested changes

2023-11-03 17:18 UTC, pmokeev commented on octreelib/grid/grid.py
> +                color = random.randrange(0, 2 ** 24)
> поскольку боги рандома
Шанс 1 к 2^24 :smile:

Согласен что `2 ** 24` нечитаемо, переделал на `0xFFFFFF`, кажется так более интуитивно должно быть, в связке с названием переменной `color`

2023-11-03 17:19 UTC, pmokeev commented on octreelib/grid/grid.py
> +                    point_size=0.1,
Ага, вынес вообще конфиг визуализации в отдельный `dataclass`, добавил поле `point_size`

2023-11-03 17:22 UTC, pmokeev commented on octreelib/grid/grid.py
> +                width=0.01,
Размер линии добавил в конфигурацию, для `0xFF0000` накинул комментарий, что это красный цвет

2023-11-03 17:23 UTC, pmokeev commented on octreelib/grid/grid_base.py
> +    visualization_filepath: str = ""
Ага, обозвал его `visualization.html`

2023-11-03 17:26 UTC, pmokeev commented on octreelib/grid/grid.py
> +                indices=[
[Коммент](https://youtu.be/mJ5t1Oe8Gzo?si=eEah1wFDcGs8L0my)

Добавил :smile:

2023-11-03 17:27 UTC, pmokeev commented on octreelib/grid/grid_base.py
> +    2. VOXEL - colors in same colors voxels belonging to different poses
renders looks nice for this case, but my English is the capital of Great Britain

2023-11-04 07:00 UTC, true-real-michael approved these changes

2023-11-04 07:01 UTC, merged