MultiPoseManager
true-real-michael/octreelib pull request #17
Opened 2023-11-09 12:26 UTC by true-real-michael

2023-11-14 17:17 UTC, pmokeev requested changes

2023-11-14 17:17 UTC, pmokeev commented on octreelib/grid/grid.py
> +    octree_config: OctreeConfig = field(default_factory=lambda: OctreeConfig())
И ваще зочем это тут, это же в `OctreeManager` по идее быть должно, нет?

2023-11-14 17:17 UTC, pmokeev commented on octreelib/octree_manager/octree_manager.py
> +        self.__empty_octree = self._octree_type(octree_config, corner_min, edge_length)
Про читаемость обсудили

2023-11-14 17:35 UTC, true-real-michael commented on octreelib/octree_manager/octree_manager.py
> +        self.__empty_octree = self._octree_type(octree_config, corner_min, edge_length)
да, заменил

2023-11-15 10:35 UTC, pmokeev commented on octreelib/grid/grid.py
> +    octree_config: OctreeConfig = field(default_factory=lambda: OctreeConfig())
Кажется, было бы логичнее всю эту схему по принципу матрешки собирать, чтобы завязываться на абстракции. В силу того что (я так понимаю) думаем, как можно избавиться от `OctreeManager` и перенести его методы в `Grid`, то наверное это поле само собой пропадет в будущем

2023-11-15 10:45 UTC, pmokeev requested changes

2023-11-15 10:45 UTC, pmokeev commented on octreelib/grid/grid.py
> +    debug: debug mode
![image](https://github.com/true-real-michael/octreelib/assets/75482510/c5114ebc-1be7-41d8-a268-d0d61b126937)
Почти все комментарии такие 😄

2023-11-15 10:45 UTC, pmokeev commented on octreelib/grid/grid.py
> +                // self._grid_config.grid_voxel_edge_length
`grid_voxel_edge_length` кажись можно переименовать, а то обращение какое-то `grid.grid_config.grid_edge_len`

2023-11-15 10:45 UTC, pmokeev commented on octreelib/grid/grid.py
> +    octree_config: OctreeConfig = field(default_factory=OctreeConfig)
Падажжи, а зачем оно вообще, если в `GridBase` эти поля есть?

2023-11-15 10:45 UTC, pmokeev commented on octreelib/grid/grid_base.py
>      grid_voxel_edge_length: int = 1
Вранье, он может быть не интом 😄

2023-11-15 10:45 UTC, pmokeev commented on octreelib/octree/octree.py
> +            self._children = []
Я в голове чот покрутил что это за кейс и не понял. Можешь пояснить, пожалуйста?

2023-11-15 10:51 UTC, true-real-michael commented on octreelib/grid/grid.py
> +    octree_config: OctreeConfig = field(default_factory=OctreeConfig)
в базовом конфиге я указал базовые классы (которые по причине своей базовости и работать-то не будут), а тут переопределил на их реализации. Вероятно, в GridConfigBase стоит писать эти параметры не OctreeBase, а сразу Octree, и конфиг аналогично

2023-11-15 10:52 UTC, true-real-michael commented on octreelib/octree/octree.py
> +            self._children = []
Если вдруг уже поделились, и получаем команду subdivide_as, то можем получить ситуацию, когда какое-то деление необходимо убрать — слить дочерние воксели в один. В пайплайне такое не предусмотрено, но в общем случае такое произойти может

2023-11-15 11:01 UTC, true-real-michael commented on octreelib/internal/voxel.py
> +from __future__ import annotations
нене, сломаются именно аннотации
<img width="804" alt="Screenshot 2023-11-15 at 14 00 29" src="https://github.com/true-real-michael/octreelib/assets/64229743/412b61c0-9047-465e-b83d-da612109d02f">

https://peps.python.org/pep-0563/

2023-11-15 11:04 UTC, true-real-michael commented on octreelib/grid/grid.py
> +    octree_config: OctreeConfig = field(default_factory=OctreeConfig)
нам нужно пробросить это в OctreeManager как-то, а взаимодействуем мы только с Grid
и поэтому пробрасываем через GridConfig

2023-11-15 11:04 UTC, true-real-michael commented on octreelib/grid/grid_base.py
>      grid_voxel_edge_length: int = 1
исправил

2023-11-15 11:07 UTC, true-real-michael commented on octreelib/grid/grid.py
> +                // self._grid_config.grid_voxel_edge_length
переименовал в voxel_edge_length

2023-11-15 11:12 UTC, true-real-michael commented on octreelib/grid/grid.py
> +    debug: debug mode
не то чтобы там есть что писать....

2023-11-15 11:13 UTC, true-real-michael commented on octreelib/grid/grid.py
> +    octree_config: OctreeConfig = field(default_factory=lambda: OctreeConfig())
вероятно так

2023-11-15 13:11 UTC, true-real-michael commented on octreelib/grid/grid.py
> +    debug: debug mode
описал несколько подробнее

2023-11-15 13:17 UTC, true-real-michael commented on octreelib/grid/grid.py
> +    octree_config: OctreeConfig = field(default_factory=OctreeConfig)
убрал переопределения

2023-11-15 13:34 UTC, pmokeev commented on octreelib/internal/voxel.py
> +from __future__ import annotations
В одинарные кавычки заключи

2023-11-15 13:38 UTC, pmokeev requested changes

2023-11-15 13:38 UTC, pmokeev commented on test/grid/test_grid.py
> +                octree_manager_type=Octree,
Тут что-то не так с неймингом\типами как будто

2023-11-15 13:38 UTC, pmokeev commented on test/grid/test_grid.py
> +                octree_type=OctreeManager,
Такая же история

2023-11-15 14:35 UTC, true-real-michael commented on test/grid/test_grid.py
> +                octree_type=OctreeManager,
💀

2023-11-15 14:35 UTC, true-real-michael commented on test/grid/test_grid.py
> +                octree_manager_type=Octree,
💀

2023-11-15 14:42 UTC, true-real-michael commented on test/grid/test_grid.py
> +                octree_manager_type=Octree,
это проверка, что при неправильном типе вылетает exception

<img width="557" alt="Screenshot 2023-11-15 at 17 41 48" src="https://github.com/true-real-michael/octreelib/assets/64229743/15fb56d7-da89-4456-9b0a-b9b50769f5c3">

2023-11-15 14:42 UTC, true-real-michael commented on test/grid/test_grid.py
> +                octree_type=OctreeManager,
это проверка, что при неправильном типе вылетает exception

<img width="557" alt="Screenshot 2023-11-15 at 17 41 48" src="https://github.com/true-real-michael/octreelib/assets/64229743/15fb56d7-da89-4456-9b0a-b9b50769f5c3">

2023-11-15 15:12 UTC, true-real-michael commented on octreelib/internal/voxel.py
> +from __future__ import annotations
done

2023-11-16 07:56 UTC, true-real-michael commented on test/grid/test_grid.py
> +                octree_manager_type=Octree,
заменил на type(None)

2023-11-16 15:59 UTC, pmokeev approved these changes

2023-11-16 16:02 UTC, merged