feat: implementation
true-real-michael/octreelib pull request #2
Opened 2023-09-27 16:37 UTC by true-real-michael

2023-10-03 17:26 UTC, pmokeev requested changes
Очень хочется комментариев, пусть даже на русском пока шишки себе набиваем

2023-10-03 17:26 UTC, pmokeev commented on test/grid/__init__.py
> +import test.grid.test_static_grid as test_static_grid_module
Я не уверен, что тесты нужно импортить, если честно

2023-10-03 17:26 UTC, pmokeev commented on test/octree/__init__.py
> +import test.octree.test_octree as test_octree_module
Сейм комментарий про тесты

2023-10-03 17:26 UTC, pmokeev commented on octreelib/grid/grid_base.py
> +from internal.typing import Point, PointCloud, T
Чото как будто с путем не то, кажется должно быть `octreelib.internal.typing `?

2023-10-03 17:26 UTC, pmokeev commented on octreelib/grid/static_grid.py
> +from .grid_base import GridBase, GridConfigBase
Тоже беды с импортом

2023-10-03 17:26 UTC, pmokeev commented on octreelib/grid/static_grid.py
> +    def get_points(self, pos: int) -> List[Point]:
pos -> pose_number. Как правильно подметил у меня в ревью Кирилл, pose это скорее матрица 4х4

2023-10-03 17:26 UTC, pmokeev commented on octreelib/grid/static_grid.py
> +            self.octrees[pos].filter()
`octree.filter(filter_criteria)` ?

Я пока не на столько в фильтрах прошарен, но мне кажется лучше чот такое сделать. Тем более ниже ты принудительно попаешь октри, где нет ничего. Мне кажется это лушче отдать на откуп filter методам передаваемым

2023-10-03 17:26 UTC, pmokeev commented on octreelib/grid/static_grid.py
> +    def filter(self, finter_criterion: Callable[[PointCloud], bool]):
`filter_criteria`*

А еще это List

2023-10-03 17:26 UTC, pmokeev commented on octreelib/grid/static_grid.py
> +        max_z = max(points, key=lambda point: point[2])[2]
В open3d есть метод специальный для этого - [тык](https://github.com/pmokeev/voxel-slam/blob/main/slam/octree/depth_octree/depth_octree.py#L45)

А вообще, мы с Анастасией на созвоне в сентябре это уже обсуждали: когда ты берешь просто максимальную и минимальную точки облака, то у тебя получается скорее "параллелепипед", чем "куб", а с этим чото надо делать. Маякни в дискорде если понял проблему

2023-10-03 17:26 UTC, pmokeev commented on octreelib/grid/static_grid.py
> +    def insert_points(self, pos: int, points: List[Point]) -> None:
pos -> pose_number

2023-10-03 17:26 UTC, pmokeev commented on octreelib/grid/static_grid.py
> +from internal import Point, T, PointCloud
Ну ты понял

2023-10-03 17:26 UTC, pmokeev commented on octreelib/grid/static_grid.py
> +    def merge(self, merger: Any):
Жди меня и я приду...

Только очень жди....

2023-10-03 17:26 UTC, pmokeev commented on octreelib/octree/octree.py
> +                child.subdivide(subdivision_criteria)
Что за магия здесь происходит? Чот понять не могу

2023-10-03 21:31 UTC, true-real-michael commented on octreelib/grid/static_grid.py
> +    def merge(self, merger: Any):
петергоф пунк работаем

2023-10-04 17:25 UTC, pmokeev commented on octreelib/octree/octree_base.py
> +from internal import Voxel
Кажись что-то не так с импортом

2023-10-04 17:26 UTC, pmokeev commented on test/__init__.py
Так его может вообще удалить?

2023-10-04 17:26 UTC, pmokeev commented on test/octree/__init__.py
Сейм

2023-10-04 17:27 UTC, pmokeev commented on octreelib/octree/octree_base.py
> +        filter nodes with points by criterion
Filters octets of octree by chosen criterion

2023-10-04 17:27 UTC, pmokeev commented on octreelib/octree/octree_base.py
> +        :param filtering_criteria:
И чо это такое?

2023-10-04 17:28 UTC, pmokeev commented on octreelib/octree/octree_base.py
> +    def filter(self, filtering_criteria: List[Callable[[PointCloud], bool]]):
А этот метод кажись в Voxel можно вынести, `OctreeNodeBase` тоже его имеет

2023-10-04 17:29 UTC, pmokeev commented on octreelib/octree/octree_base.py
Я не уверен что пробелы нужны здесь. Посмотри пж как у Артура, например, [комментарии к классам сделаны](https://github.com/achains/voxel-slam/blob/main/voxel_slam/backend/base_backend.py#L7)

2023-10-04 17:31 UTC, pmokeev commented on octreelib/grid/static_grid.py
> +        for pos_n in self.octrees:
pos_n -> pose_number

2023-10-04 17:31 UTC, pmokeev commented on octreelib/grid/static_grid.py
> +        for pos_n in self.octrees:
А почему ты здесь не хочешь, как ниже в `subdivide` сделал?

2023-10-04 17:33 UTC, pmokeev commented on octreelib/grid/static_grid.py
> +                self.octrees.pop(pos_n)
Не надо ничего попать, оставь пока просто пусть циклом пробегается. Я уже писал что эта логика будет в `filtering_criteria` методе

2023-10-04 17:41 UTC, pmokeev commented on octreelib/octree/octree.py
> +                child.subdivide(subdivision_criteria)
Похоже на правду

2023-10-04 17:42 UTC, pmokeev commented on octreelib/grid/static_grid.py
> +
Лишний отступ как будто бы

2023-10-04 17:45 UTC, pmokeev commented on octreelib/octree/octree.py
> +            self.points = []
У меня пока нет внятного понимания как должны работать фильтры, надо будет этот момент проработать

2023-10-04 17:47 UTC, true-real-michael commented on octreelib/octree/octree_base.py
> +from internal import Voxel
ну дела

2023-10-04 18:01 UTC, true-real-michael commented on octreelib/grid/static_grid.py
> +        for pos_n in self.octrees:
если октодерево пустое, то в рамках статической сетки (т.е. больше не добавляем точек), нам не нужно его хранить

2023-10-04 18:03 UTC, true-real-michael commented on octreelib/grid/static_grid.py
> +                self.octrees.pop(pos_n)
Вроде filtering_criteria -- это же просто функции, которые возвращают bool и на основании которых мы принимаем решение об удалении точек
А если нет точек ни в одном дочернем узле, то их можно объединить

2023-10-04 18:04 UTC, true-real-michael commented on octreelib/grid/static_grid.py
> +
отделение импортов библиотек от импортов собственных файлов

2023-10-05 11:54 UTC, true-real-michael commented on octreelib/grid/static_grid.py
> +        max_z = max(points, key=lambda point: point[2])[2]
с этим нет проблем
строчкой ниже выбирается длина ребра куба, а октодерево инициализируется по одной точке и длине ребра, так что получается всегда куб

2023-10-05 11:54 UTC, true-real-michael commented on octreelib/octree/octree.py
> +            self.points = []
тоже, действительно, фильтры, сабдивайды и мерж надо поштормить, подумать, как нам будет наиболее удобно

2023-10-05 14:46 UTC, true-real-michael commented on octreelib/octree/octree_base.py
> +    def filter(self, filtering_criteria: List[Callable[[PointCloud], bool]]):
filter не имеет смысла для Voxel, поскольку у Voxel нет дочерних объектов, на которые мог бы подействовать фильтр

2023-10-05 14:47 UTC, true-real-michael commented on octreelib/octree/octree_base.py
без пустых строк столкнулся с плохим отображением в пайчарме, но, да, нужно поменять

2023-10-14 16:14 UTC, pmokeev requested changes
И давай переедем со всяких `List` на `numpy`

2023-10-14 16:14 UTC, pmokeev commented on octreelib/grid/static_grid.py
> +        self, pos_number_1: int, pos_number_2: int
`pos_number_1` -> `first_pose_number`

`pos_number_2` -> `second_pose_number`

2023-10-14 16:14 UTC, pmokeev commented on octreelib/grid/static_grid.py
> +        octree_1 = self.octrees[pos_number_1]
Давай не будем использовать числа в именах переменных. 

https://stackoverflow.com/a/76150376

2023-10-14 16:14 UTC, pmokeev commented on octreelib/internal/converters.py
What does this file do?

2023-10-14 16:14 UTC, pmokeev commented on octreelib/grid/static_grid.py
> +        ) + octree_2.get_points_inside_box(intersection_box)
Это black так форматнул?

2023-10-14 16:14 UTC, pmokeev commented on octreelib/internal/geometry.py
> +def boxes_intersection(box_1: Box, box_2: Box) -> Optional[Box]:
Про нейминг и цифры в переменных писал уже

2023-10-14 16:14 UTC, pmokeev commented on octreelib/internal/geometry.py
> +def boxes_intersection(box_1: Box, box_2: Box) -> Optional[Box]:
Может лучше назвать `intersect_boxes` ? Почему бы этот метод не вытащить в класс Box?

`first_box.intersect(another_box)` ?

2023-10-14 16:14 UTC, pmokeev commented on octreelib/internal/geometry.py
> +def point_is_inside_box(point: Point, box: Box) -> bool:
Тоже кажется ни к чему этому методу быть отдельным

2023-10-14 16:14 UTC, pmokeev commented on octreelib/octree/octree.py
> +        return self.root.n_node
Видимо оно уже пофикшено, но для контекста оставлю комментарий что оно не работало раньше

2023-10-15 08:54 UTC, true-real-michael commented on octreelib/grid/static_grid.py
> +        ) + octree_2.get_points_inside_box(intersection_box)
йеп

2023-11-04 20:21 UTC, closed without merging